---

- hosts: projeto-homolog
  remote_user: testcloud_ub
  sudo: yes

  tasks:

  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - build-essential
      - npm
      - nodejs-legacy
      - nodejs
      - git
      - mcrypt
      - curl
      - nginx
      - redis-server
      - redis-tools
      - mongodb
      - mongodb-clients
      - mongodb-server
      - openjdk-8-jdk

  - service: name=mongodb state=started
  - service: name=redis state=started
  - service: name=nginx state=started

  - name: Install RVM
    shell: "curl -sSL https://get.rvm.io"

  - name: Load RVM function
    shell: echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc

  - name: Download NODE
    shell: "curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -"

  - name: Install NODE
    apt: name=nodejs

  - name: Install NPM
    shell: "npm install npm -g"

  - name: Install PM2
    npm: name=pm2 global=yes production=yes

  - name: Install pm2
    shell: "npm install pm2 -g"

  - name: Install packages to install android sdk
    apt: name={{ item }} state=installed
    with_items:
     - libncurses5
     - libstdc++6
     - zlib1g
     - imagemagick
     - expect
     - gradle
     - ant
     - ccache
     - autoconf
     - automake
     - ant
     - ccache
     - python-dev
     - zlibc
     - libsane

  - name: Download sdk tools
    get_url: >
     url=http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
     dest=/opt/android-sdk_r23.0.2-linux.tar.gz
    register: sdk_file

  - name: Unarchive sdk tools
    command: >
     tar xzf {{ sdk_file.dest }}
     creates=/opt/android-sdk-linux
     chdir=/opt
  - name: Set envs for android sdk
    copy: >
     src=android.sh
     dest=/etc/profile.d/android.sh

  - name: Install Android SDKs
    shell: echo y | android update sdk -u -a -t "{{ item }}"
    with_items:
     - tools
     - platform-tools
     - build-tools-19.1.0
     - android-20
     - android-19
     - android-18
     - android-17
     - extra-android-support
